---
title: "Educational Attainment in UK"
author: "Na Nguyen"
date: "2024-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidytuesdayR)
library(readr)
tuesdata <- tidytuesdayR::tt_load('2024-01-23')

english_education <- tuesdata$english_education

# Option 2: Read directly from GitHub

english_education <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-01-23/english_education.csv')

englishED_income <- read_csv("../data/keystage.csv")


```
```{r}
english_education %>% 
  filter(!is.na(income_flag )) %>% 
  ggplot(aes(x = key_stage_2_attainment_school_year_2007_to_2008)) + 
  geom_density(aes(fill = income_flag), alpha = .7)
```
```{r}
english_education %>% 
  filter(!is.na(income_flag )) %>% 
  ggplot(aes(x = key_stage_4_attainment_school_year_2012_to_2013)) + 
  geom_histogram(aes(fill = income_flag), alpha = .7) +
  facet_wrap (~income_flag)
```
```{r}
english_education %>% 
  filter(!is.na(income_flag )) %>% 
  ggplot(aes(x = key_stage_4_attainment_school_year_2012_to_2013)) + 
  geom_density(aes(fill = income_flag), alpha = .7)
```
```{r}
library(dplyr)
library(tidyr)
library(distributional)
library(ggdist)
library(ggplot2)
library(patchwork)
library(palmerpenguins)
```





```{r}
# Cleaning Data
english_education_clean <- english_education %>% 
    select(key_stage_2_attainment_school_year_2007_to_2008, key_stage_4_attainment_school_year_2012_to_2013,level_3_at_age_18, activity_at_age_19_full_time_higher_education, income_flag, size_flag, education_score) %>%
  filter(!is.na(income_flag))  %>% 
    mutate(income_flag = ifelse(income_flag == "Cities", "Higher deprivation towns", income_flag)) %>% 
  rename(key_stage_2 = key_stage_2_attainment_school_year_2007_to_2008,
         key_stage_4 = key_stage_4_attainment_school_year_2012_to_2013,
         level_3_age_18 = level_3_at_age_18,
         higher_ed_19 = activity_at_age_19_full_time_higher_education) %>% 

  pivot_longer(cols = 1:4, names_to = "ed_attainment_level", values_to = "proportion") 

ed_levels_factored <-  factor(c("key_stage_2", "key_stage_4", "level_3_age_18", "higher_ed_19"))
income_flag_factored <- factor(c("Lower deprivation towns", "Mid deprivation towns", "Higher deprivation towns"))

english_education_clean <- english_education_clean %>% 
  mutate(ed_attainment_level = factor(ed_attainment_level, ed_levels_factored )) %>% 
  mutate(income_flag = factor(income_flag, income_flag_factored))
```

```{r}
# Set theme
theme_customization =  theme_minimal() +
   theme(plot.title = element_text(size = 18, face = "bold"),
            plot.subtitle = element_text(size = 14),
            axis.title.y = element_blank(),
            text = element_text(size = 14, vjust = 1))

  theme(plot.title = element_text(family = "Helvetica", size = 12, face = "bold"),
        axis.title.y = element_blank())

```

```{r}
library(plotly)
library(ggplot2)
library(ggridges)

# Will be filtered based on Ed_level

ggplot(english_education_clean, aes(x = proportion, y = income_flag, fill = stat(quantile))) +
  stat_density_ridges(quantile_lines = FALSE,
                      calc_ecdf = TRUE,
                      geom = "density_ridges_gradient") +
  scale_fill_brewer(name = "Quantile",palette = 1 ) +
  scale_x_continuous(breaks = seq(10, 100, by = 10), limits = c(10, 100)) +
  theme_minimal() +
  labs( x = "Achieved Proportion of Town",
       title = "Educational outcomes are worse in income deprived towns",
       subtitle = "Data: The UK Office for National Statistics") +
  theme(plot.title = element_text(family = "Helvetica", size = 12, face = "bold"),
        axis.title.y = element_blank())


```

```{r}

english_education_clean %>% 
  ggplot(aes(y = size_flag, fill = income_flag)) +
  geom_bar(position = "fill", width = .4) +
  labs( fill = "Income Level",
        title = "Smaller are less likely to be income deprived ") +
  theme_minimal()+
  theme_customization
```
```{r}
# Will be filtered based on Ed_level

 english_education_clean %>% 
      ggplot(aes(x = proportion, y = education_score)) +
      geom_point(shape =1,  alpha =.7, color = "#386cb0") +
      geom_smooth(color = "red3") +
      labs( title = "Education Score vs. Achieved Proportion",
            subtitle = "Education Score based on attainment levels of the 2012/13 Key stage 4 cohort.",
            y = "Education Score",
            x = "Achieve Proportion") +
      scale_fill_brewer()+
      theme(plot.title = element_text(vjust = -1)) +
      theme_minimal() +
      theme(plot.title = element_text(size = 18, face = "bold"),
            plot.subtitle = element_text(size = 10),
            text = element_text(size = 14, vjust = 1))
```

